# Generated by Django 5.2.8 on 2025-11-22 17:36

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_resena_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validar_no_vacio]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validar_no_vacio]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(validators=[biblioteca.models.validar_resumen_minimo]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validar_no_vacio]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(validators=[biblioteca.models.validar_calificacion]),
        ),
    ]
