# Generated by Django 5.2.8 on 2025-11-22 18:41

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_resena_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(error_messages={'blank': 'La nacionalidad no puede estar vacía.'}, max_length=100, validators=[biblioteca.models.validar_nacionalidad_sin_numeros]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El nombre no puede estar vacío.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(validators=[biblioteca.models.validar_resumen_minimo]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(error_messages={'blank': 'El titulo no puede estar vacío.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(validators=[biblioteca.models.validar_calificacion]),
        ),
    ]
