# Generated by Django 5.2.8 on 2025-11-22 17:58

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_autor_nacionalidad_alter_autor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, validators=[biblioteca.models.validar_no_vacio]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, validators=[biblioteca.models.validar_no_vacio]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, validators=[biblioteca.models.validar_no_vacio]),
        ),
    ]
